Обновил README.md
DotNetRu/Server pull request #141
Opened 2021-05-03 13:05 UTC by zetroot

Пока в двух словах под новые реалии. Добавил бейджиков сборки и покрытия тестами.
Надо будет только url у бейджей обновить, когда заедут новые actions

2021-05-04 21:24 UTC, ilabutin requested changes
Вмержил первый PR. сборка прошла. Обновишь URL у бейджей?
А также допиши как смотреть на то что собрано (и лежит в gh-pages)

2021-05-04 21:30 UTC, zetroot commented
Ок!
Бейджмки обновлю завтра.
Для включения github pages надо сделать шаги, описанные [тут](https://guides.github.com/features/pages/)
После этого все будет доступно на [https://dotnetru.github.io/Commune](https://dotnetru.github.io/Commune)

2021-05-04 21:49 UTC, zetroot commented
Обновил бейджики.
Статистика по покрытию тестами доступна [тут](https://app.codecov.io/gh/DotNetRu/Commune).
Можно заливать.

2021-05-05 05:12 UTC, ilabutin commented
@kulakovt Создать github pages это тебе - там нужно новый repository создавать по идее.

2021-05-05 05:13 UTC, zetroot commented
@ilabutin вроде бы нет. Эту фичу можно (и нужно!) включить в текущем репозитории, ведь пушит он именно туда.

2021-05-05 19:11 UTC, merged