Features/fb 22
DotNetRu/Server pull request #30
Opened 2018-05-17 15:52 UTC by a-merson

Proof-of-concept for Anaemic Domain Model with onion layers

2018-05-17 23:05 UTC, kulakovt requested changes

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
У нас в моделе идентификаторы строковые

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public string SpeakerName { get; set; }
Хотелось бы иметь возможность задавать несколько спикеров

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        //public IReadOnlyCollection<TalkTryout> Tryouts { get; set; }
Т.к. из Черновика будет формироваться Чистовик (#29), здесь должно быть достаточно полей для корректной публикации [Докладчика](https://github.com/DotNetRu/Audit/blob/master/schemas/Speaker.xsd) и [Доклада](https://github.com/DotNetRu/Audit/blob/master/schemas/Talk.xsd). Сейчас информации явно не хватает

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/Events/TalkTryoutCommited.cs
> +    public class TalkTryoutCommited
Для "Тренировок" мы используем слово "Rehearsal"

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/ITalkTryoutService.cs
> +        void AttachArtifacts(long tryoutId, byte[] artifacts);
Артифакты сейчас Дравту не нужны. Я не вижу пока для них никакой нагрузки. А они элементарно добавляются, ежели таковая появится. Все предварительные слайды нет никакого смысла хранить в базе. Максимум это ссылка, которуя я запишу в Заметки к тренировке.

2018-05-17 23:05 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +    }
Может стоит добавить Id пользователя который добавлял драфтовую сущность? 

Тогда можно будет хитро отсортировать, чтобы сначала каждый видел "свои" записи, а остальные например по дате обновления.

2018-05-17 23:05 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Ещё хочется "Дату и время проведения", а также "Окончания"

2018-05-17 23:05 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Может пространство должно быть не "Core", а "Model"? И не "Shared", а "Published"?

2018-05-17 23:08 UTC, AnatolyKulakov commented
Правильно я понимаю, что для попадания в `master` необходимо:

1. согласовать модели?
1. заполнить полностью её полями?
1. реализовать инфраструктуру для EF?

Или цель этой работы только первый пункт, а остальное мы сделаем в следующих пул-реквестах?

2018-05-18 07:50 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +    }
У нас пока нет пользователей, и аутентификации. Можно потом добавить

2018-05-18 08:52 UTC, Sergey-Buyanov commented
@a-merson можешь подправить, чтобы проект собирался, и сделать pull request в features/domain-model?

2018-05-18 08:56 UTC, Sergey-Buyanov commented
@AnatolyKulakov для попадания
1) + 
2) Не много не понял? Добавить все нужные поля в модели и сервисы?
3) Это уже будем делать отдельными тасками

2018-05-18 08:59 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Да нужно будет подумать по именованию. Я бы назвал пространство Domain, т.к. там будут не только модели, но и сервисы.

2018-05-18 10:27 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
В базе ты тоже хочешь строковый primary key?

2018-05-18 10:31 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Core - так принято в onion-архитектуре, т.к. домен в центре. Shared - это означает общее, к паблишу отношения не имеет.

2018-05-18 16:59 UTC, EngineerSpock commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Дату и время будем через NodaTime или стандартным DateTime?

2018-05-18 17:00 UTC, EngineerSpock commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Согласен с Алексеем. Насколько помню, всё так и есть.

2018-05-18 19:38 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Я точно не хочу разрабатывать свою модель опираясь на ограничения конкретной базы. Мы же вроди как про "предметную область" говорим, и про персистент-агностик. Какая мне разница что там будет в базе?

2018-05-18 19:40 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +    }
Да, точно. Тогда отложим на потом. И надо будет накатать Epic про Auth.

2018-05-18 19:44 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Это сильно зависит от обсуждаемого в "чатике DDD" моего вопроса про сторонние библиотеки в Домене. NodeTime типичный представитель такой библиотеки. Надо определиться: должен ли домен её использовать или нет, напрямую или через интерфейс и т.д.

2018-05-18 19:54 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
"принято" это конечно хорошо, но хотелось бы ещё понимать и почему так принято. Есть что почитать? Ибо название "Domain" намного очевиднее и понятнее, чем "Core".

> Shared - это означает общее, к паблишу отношения не имеет.

Но в этой папке лежит реально Published сущность - `Community`, которая никакого отношения к Shared не имеет. Она совсем ни разу не "общее"!

2018-05-18 19:57 UTC, AnatolyKulakov commented
2. Ну да. Стоит ли мне в рамках данного обсуждения полностью описывать все поля которые нам нужны (и не нужны) в Домене Черновиков? Или это своеобразный PoC чтобы продемонстрировать подход и всё, полнота Модели тут не важна.

2018-05-18 21:55 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Да согласен, с @AnatolyKulakov, ещё не всегда бизнес сущность маппится один в один форматом хранения в базе. Там возможны различные преобразования, например времени.

2018-05-18 21:57 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Давайте использовать DateTimeOffset в домене. Вроде с ним не должно быть проблем.

2018-05-18 22:05 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Вот варианты схемы с onion
https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html
https://blog.tonysneed.com/2011/10/08/peeling-back-the-onion-architecture
Я так понимаю нет строго правила в наименовании
В последней ссылке, просто Core, немного общее название и человека незнакомого может сбивать столку

2018-05-18 22:14 UTC, Sergey-Buyanov commented
Я думаю сейчас решим остальные вопросы, зачекиню в branch и уже добавим все поля, чтобы была уже готовая схема к реализации

2018-05-19 06:02 UTC, AnatolyKulakov commented
Я пытаюсь определить, какие вопросы надо решить, чтобы это попало в `master`?

2018-05-19 06:40 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Невозможно быть абсолютно персистент агностик. Либо это будет очень дорого. Id/primary key - это как раз то место, где лучше быть persistent aware. Практически в любой базе у тебя встанет этот вопрос.

2018-05-19 10:05 UTC, Sergey-Buyanov commented
Да, тогда надо будет определить все поля и все типы, то что нужны для черновиков, сейчас модели есть WebApi.Contract, можно будет оттуда взять, если не будет вопросов, это уже можем сами по аналогии

2018-05-19 10:19 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Тут тонкий момент, с одной стороны хотелось, чтобы клиенты не привязывались к типу ключа, т.к. это даёт проще менять формат и схему хранения (т.к. эти типы будут пролезать в другие классы и возрастает сложность измений, например long на Guid). C другой стороны, если так делать, то где-то нужно делать проверку  (можно проверять при создании модели или сохранении). В любом случае в Rest будет string.
Также в базе по тем или иным причинам может быть свой внутренний InternalId (primary key) и внешний.

2018-05-19 10:30 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Поддерживаю DateTimeOffset. Но если бы у нас была _реальная_ необходимость в NodeTime, то её можно было бы втащить в домен. Потому что эта библиотека инкапсулирует домен даты-времени и наш домен, используя проперти такого типа, является клиентом этого домена. То есть это явная и естественная зависимость.

2018-05-19 10:56 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Делить на Interfaces, Entities и тому подобное точно плохо (см. Вернона), а так можно и domain, если сохранится понимание, что это ядро без сторонних зависимостей.

2018-05-19 12:12 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Давайте тогда Domain

2018-05-19 12:14 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/TalkTryout.cs
> +        public string Comment { get; set; }
Да согласен, если была бы необходимость то можно было бы использовать.

2018-05-21 11:27 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
> Но в этой папке лежит реально Published сущность - Community, которая никакого отношения к Shared не имеет. Она совсем ни разу не "общее"!
А будет DraftCommunity? Мне так казалось, что Community - это сущность уровнем выше, над всеми остальными. И поэтому, собственно, я положил ее в Shared.

2018-05-22 19:29 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Действительно, если базе нужен определённый ключ, то может не надо пытаться его завязывать на домен? Естественные ключи не обязательно должны совпадать с хранилищем, можно иметь и несколько полей.

Кстати, ничего не мешает сделать primary key строкой. У этого подхода нет технических минусов во всех нормальных БД.

2018-05-22 19:35 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
DraftCommunity слабо-представляю, а вот "Community Candidate" у нас есть :)
Основной смысл в том, то нельзя быть уверенным что в будущем не появится другой аспект Community, который будет конфликтовать с Shared Community, поэтому лучше точно отнести её к Published, чем она и является.

2018-05-22 19:38 UTC, AnatolyKulakov commented
@Sergey-Buyanov , не понял. Что мы делаем в рамках этого пул-реквеста? Мы просто смотрим на него и когда у всех кончатся комментарии будет делать "сами по аналогии" полную модель? Или мы доводим его до полной модели?

2018-05-22 19:49 UTC, kulakovt requested changes

2018-05-22 19:49 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long Id { get; set; }
А не хотим ли мы ещё заморочаться с Primitive Obsession проблемой? Хотя бы для идентификаторов. Очень, мне кажется, полезная вещь.

http://blog.ploeh.dk/2011/05/25/DesignSmellPrimitiveObsession/
https://enterprisecraftsmanship.com/2015/03/07/functional-c-primitive-obsession/

2018-05-22 21:19 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
Технический минус как минимум в обеспечении гарантий уникальности и в индексах. Но я не вижу смысла дальше обсуждать этот момент.

2018-05-22 21:29 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
CommunityId должно быть атрибутом большинства сущностей. И это будет реально существующее CommunityId. Поэтому оно и получается общим. Flow 'Potential-Draft-Published' мы обсуждали в другом контексте, я считаю большой ошибкой пытаться впихнуть в него ~~невпихуемое~~ Community.

2018-05-22 21:30 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long Id { get; set; }
Я точно не хочу :)

2018-05-24 07:57 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long Id { get; set; }
Надо посмотреть, возможно завести тип наподобие, UniqueIdentifier или TalkId. Но надо подумать какой профит это принесет в данном случае

2018-05-24 08:37 UTC, Sergey-Buyanov commented
@AnatolyKulakov планы такие мержу https://github.com/DotNetRu/Server/pull/31 в правильный branch, изменяем дописываем модели в нём

2018-05-24 09:15 UTC, kulakovt commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long CommunityId { get; set; }
В чём минус? Констрейнты проверяют уникальность независимо от типа ключа. Естественно строки тоже могут быть гарантированно проверены в индексах на уникальность. У этого подхода действительно нет технических отличий от `long` ключа.

2018-05-24 09:20 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
Сущность `Community` вообще ничем не отличается от всех остальных (`Meetup`, `Friends`). У неё нет никаких особенностей, которые бы позволяли начать думать о ней не так как о других.

> CommunityId должно быть атрибутом большинства сущностей

Это не верное утверждение. Ссылка на `CommunityId` будет только в одном месте: в `Meetup`.

2018-05-24 09:21 UTC, AnatolyKulakov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long Id { get; set; }
«Профит» описан в статьях выше.
Из своей личной практики — огромный!

2018-05-24 09:27 UTC, AnatolyKulakov commented
@Sergey-Buyanov , если этот пул-реквест не отвечает полностью ни на один из трёх вопросов (см. выше), а все эти аспекты необходимо дорабатывать, то зачем его мёржить? Может лучше тогда воспользоваться им как PoC'ом? Т.е. посмотреть идеи, сформулировать отдельно 3 таски, сделать их полностью с чистого листа. Мне кажется, что на это уйдёт меньше сил (а главное — будет понятно как и что ревьювить), чем пытаться причесать кучу пруфов (которые здесь).

2018-05-24 10:00 UTC, a-merson commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Shared/Community.cs
> +namespace DotNetRu.MeetupManagement.Core.Shared
> Это не верное утверждение. Ссылка на CommunityId будет только в одном месте: в Meetup.
Согласен, тут я был не прав.
>У неё нет никаких особенностей, которые бы позволяли начать думать о ней не так как о других
Но особенность есть: сущность Community не является артефактом процесса организации митапа, который мы обсуждаем. Все-таки сначала у нас есть Community, а потом уже мы организуем митап этого Community

2018-05-24 12:30 UTC, Sergey-Buyanov commented
Полностью нет, но в pull request помимо этого сделаны другие вещи  добавлены проекты, зависимости. Не очень хочется это снова делать.
Думаю просто пройтись по тому что написали и исправить.

2018-05-27 18:41 UTC, AnatolyKulakov commented
@Sergey-Buyanov , получается что здесь нам делать нечего? Давай закрывать issue? И расскажи тогда где и кто будет делать окончательные варианты задач:

1. согласовать модели;
1. заполнить полностью их полями;
1. реализовать инфраструктуру для EF.

Будет ли это одна таска или несколько?

2018-05-29 18:01 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Core/Drafts/DraftTalk.cs
> +        public long Id { get; set; }
Я не против использования, надо только определиться, что это будет. Можно пока оставить string, а после сборки всех моделей определить их.

2018-05-29 18:06 UTC, Sergey-Buyanov commented
Да, в этом pull request вроде всё обсудили.
На основе этого в [бранче](https://github.com/DotNetRu/Server/tree/features/domain-model) внесу корректировки.
После согласования моделей будут отдельные задачи на по реализации инфраструктуры для EF и интеграции с WebApi

2018-06-02 13:02 UTC, AnatolyKulakov commented
@Sergey-Buyanov , тогда закрывай этот таск. Корректируй бранч который пойдёт в мастер и зови меня туда, где надо будет уже комментировать конкретные вещи.

2019-04-18 19:29 UTC, closed without merging