Change appveyor CI. Add docker integration
DotNetRu/Server pull request #40
Opened 2018-10-03 18:33 UTC by d2funlife

Изменил CI для appveyor.

Вся линия построения и тестирования осталась в скрипте построения docker образа. Docker образ публикуется в docker hub. Ранее дополнительно обсуждали публикацию Github releases, но решили не делать автоматическую публикацию, так как автоматическое описание \ отсутствие описания не подходит. [PR 36](https://github.com/DotNetRu/Server/pull/36)

Хочу отметить, что оставил построение образа только из master ветки.

2018-10-03 18:36 UTC, egorikas commented on appveyor.yml
> +    secure: 7xusxxMFy9iURl0Ktuzri5XyT3/NDKlsU3kkfJ+Sq90=
А безопасно так хранить?

2018-10-03 18:39 UTC, d2funlife commented on appveyor.yml
> +    secure: 7xusxxMFy9iURl0Ktuzri5XyT3/NDKlsU3kkfJ+Sq90=
Безопасно. Шифрование данных: [документация](https://www.appveyor.com/docs/how-to/secure-files/)

2018-10-04 08:25 UTC, kulakovt requested changes

2018-10-04 08:25 UTC, kulakovt commented on appveyor.yml
>  - Ubuntu
Может будем билдить и гонять тесты на обоих системах?

2018-10-04 08:25 UTC, kulakovt commented on build/deploy-docker.ps1
> +docker images
А эта команда зачем здесь?

2018-10-04 08:25 UTC, kulakovt commented on appveyor.yml
> -  - Release
В #36 мы хотели сделать отдельный issue для GitHub Releases. @Sergey-Buyanov , ты её не делал? Не могу найти.

2018-10-04 08:25 UTC, kulakovt commented on appveyor.yml
> -  verbosity: minimal
Может мы всё-такие не будем удалять весь этот код по сборке? Тут очень много каких-то умных вещей написано. Мне казалось мы не ходим отказываться от компиляции и тестирования (а также проверки анализаторами качества кода). Мы просто решили не делать выкладывание артифактов в Releases вот и всё. Я надеялся следующей маленькой строчкой всё-таки доделать Releases.

2018-10-04 09:02 UTC, d2funlife commented on appveyor.yml
>  - Ubuntu
Все зависит от целей. У нас сейчас билд и тесты проходят в построении docker образа.
Если цель прогона тестов и билд проекта на другой платформе, я верну сценарий для двух платформ.

2018-10-04 09:02 UTC, d2funlife commented on build/deploy-docker.ps1
> +docker images
Вывод списка образов, информация в логи.

2018-10-04 09:02 UTC, d2funlife commented on appveyor.yml
> -  - Release
Issue не создавался. В ходе обсуждения, мы так и не решили, как будет выглядеть автоматический релиз.

2018-10-04 09:02 UTC, d2funlife commented on appveyor.yml
> -  verbosity: minimal
От компиляции и тестирования мы не отказываемся, все это есть в скрипте создания docker образа.

2018-10-04 09:14 UTC, d2funlife commented on appveyor.yml
> -  - Release
> как будет выглядеть автоматический релиз.

Имею в виду, что у нас будет сборка и номер с шаблонным текстом, если этого достаточно, я добавлю

2018-10-04 11:43 UTC, Sergey-Buyanov commented on appveyor.yml
>  - Ubuntu
Да нужно для двух платформ,
Образ у наc будет пока только для Linux

2018-10-04 11:46 UTC, Sergey-Buyanov commented on appveyor.yml
> -  verbosity: minimal
У меня вопрос, не в master ветке, что будет происходить? Там docker образ я так понимаю не собирается.

2018-10-04 12:15 UTC, d2funlife commented on appveyor.yml
> -  verbosity: minimal
Да, сборка происходит только при изменении master

2018-10-04 12:17 UTC, d2funlife commented
@Sergey-Buyanov @AnatolyKulakov Верну сборку под Windows, что с Github releases делать? Добавлять или нет ?

2018-10-04 12:19 UTC, kulakovt commented on appveyor.yml
>  - Ubuntu
Мне бы хотелось скачать собранные бинарники и запускать на локальном компе с Windows. Большинство разработчиков тоже сидит под Windows, хотелось бы быть уверенным что уних всё будет компилироваться и все тесты будут проходить.

2018-10-04 12:21 UTC, kulakovt commented on appveyor.yml
> -  - Release
Вот для этого и нужен issue, что бы там, в одном месте, всё обсудить и решить. Иначе у нас обсуждения раскиданы уже по двум местам.
@Sergey-Buyanov , можешь создать таковой?

2018-10-04 12:27 UTC, AnatolyKulakov commented on appveyor.yml
> -  verbosity: minimal
> всё это есть в скрипте создания docker образа

Хотелось бы всё-таки прогон под все (пока обе) системы. Это поможет избежать платформоспецифического кода и позволит разработчикам быть уверенными в том что их код работает везде.

Так же не хочется смешивать контейнер и CI. Т, что оно там в контейнере тестируется хорошо. Но если мы вдруг решим выкинуть Docker по каким-то соображениям, хочется чтобы на билдах (CI) это никак не сказалось. Т.е. я предлагаю оставить в AppVeyor полноценный pipeline (с билдами, тестами, анализаторами и т.д.) под все ОС. Если тоже самое будет делаться и в Docker'е, то это будет приятным бонусом. Но это не замена, это просто ещё одна конфигурация.

2018-10-04 12:29 UTC, AnatolyKulakov commented
Github Releases в этой таске не надо добавлять. Обсудим его отдельно. Тут просто не удаляй создание и проверку артифактов.

2018-10-04 18:53 UTC, Sergey-Buyanov commented on appveyor.yml
> -  - Release
Да, создам попозже

2018-10-04 20:37 UTC, d2funlife commented
@AnatolyKulakov @Sergey-Buyanov сборку оставлять только в master ветке?

2018-10-04 20:39 UTC, AnatolyKulakov commented
Контейнера точно только в мастере. А вот запуск всех тестов наверное полезно делать во всех ветках. Ну или в `dev` хотя бы...

2018-10-04 21:24 UTC, Sergey-Buyanov commented
Да всё должно проходить во всех ветках. Сборка контейнера только в master

2018-10-10 11:28 UTC, Sergey-Buyanov requested changes
@d2funlife обнови пожалуйста образы до версии 2.1

2018-10-10 11:28 UTC, Sergey-Buyanov commented on Dockerfile
>  WORKDIR /build
Change base image to latest version: microsoft/dotnet:2.1-sdk

2018-10-10 11:28 UTC, Sergey-Buyanov commented on Dockerfile
>  FROM microsoft/aspnetcore:2.0
Change to latest version Change image to latest version microsoft/dotnet:2.1-aspnetcore-runtime

2018-10-10 18:58 UTC, Sergey-Buyanov approved these changes

2018-10-10 19:06 UTC, Sergey-Buyanov commented
@AnatolyKulakov посмотри по своему request-у https://github.com/DotNetRu/Server/pull/40#pullrequestreview-161321516 и заапрувь, если всё ok

2018-10-10 19:33 UTC, kulakovt approved these changes

2018-10-10 19:33 UTC, AnatolyKulakov commented on appveyor.yml
> +    after_test:
А где `before_build`, `build_script`?

2018-10-10 19:33 UTC, AnatolyKulakov commented on appveyor.yml
> +        - master
Почему игнорируем `master`? Его артифакты тоже полезны

2018-10-10 19:36 UTC, d2funlife commented on appveyor.yml
> +        - master
Игнор для рядовой сборки Linux, полный скрипт более подробно отображает

2018-10-10 19:36 UTC, AnatolyKulakov commented
@Sergey-Buyanov , заапрувил.
Я уже наверное структуру AppVeyor'а файла забыл, всё слишком ново :)

2018-10-10 19:37 UTC, d2funlife commented on appveyor.yml
> +    after_test:
Сохранил оригинал

2018-10-10 20:38 UTC, merged