Базовая интеграция api для телеграмм ботов
DotNetRu/Server pull request #42
Opened 2018-10-13 13:16 UTC by egorikas

Добавил библиотеку
Прокинул зависимости
Добавил сервис

p.s. 
У меня большие сомнения вызывает необходимость autofac. Он конечно гибкий и чудесный, но как мне видится скоп проекта, будет достаточно наличия стандартного иньектора, он вполне ничего сейчас и уже точно быстрее autofac ( https://www.akshaysura.com/2016/08/31/ioc-container-benchmark-comparison-2016-including-microsoft-extensions-dependencyinjection/).
В autofac не нравится то, как его надо вклинивать в pipeline, не очень красиво получается

2018-10-16 20:08 UTC, Sergey-Buyanov commented
> p.s.
> У меня большие сомнения вызывает необходимость autofac. Он конечно гибкий и чудесный, но как мне видится скоп проекта, будет достаточно наличия стандартного иньектора, он вполне ничего сейчас и уже точно быстрее autofac ( https://www.akshaysura.com/2016/08/31/ioc-container-benchmark-comparison-2016-including-microsoft-extensions-dependencyinjection/).

Autofac выбирали исходя из того, что достаточно хорошо зарекомендовал и известен для разработчиков.  По поводу Microsoft DI - пока молодой и не ясно, как оно взлетит. Также думаю, если будет необходимость сможем спокойно заменить di на какой-нибудь другой.
> В autofac не нравится то, как его надо вклинивать в pipeline, не очень красиво получается
А что не понравилось?

2018-10-16 21:04 UTC, Sergey-Buyanov requested changes

2018-10-16 21:04 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Application/Services/ISocialIntegrationService.cs
> +using System.Threading.Tasks;
Ещё не продумывали, какие сервисы будут в Application Layer для публикации meetup. Скорей всего он будет другим. Так что можно это сервис пока удалить

2018-10-16 21:04 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Вроде хотели использовать IOptions<>

2018-10-16 21:04 UTC, Sergey-Buyanov commented on test/ServiceHost.Tests/ServiceHost.Tests.csproj
> +    <PackageReference Include="Moq" Version="4.10.0" />
А где используется Moq в проекте?

2018-10-16 21:04 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            await botClient.SendTextMessageAsync(_settings.ChannelName, text).ConfigureAwait(false);
Судя по описанию https://core.telegram.org/bots/api#sendmessage метод позволяет пересылать в формате markdown и html в зависимости от ParseMode. @AnatolyKulakov ты не использовал эту возможность?

2018-10-17 08:19 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Мне не очень нравится и идея, тащить Microsoft.Configuration.Extensions в слой инфраструктуры. Чисто в теории, в этом нет ничего страшного. Но я просто всегда придерживался самописных настроек, который инжектились в singletone-стиле. Если все таки IOptions, готов поменять

2018-10-17 08:20 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Application/Services/ISocialIntegrationService.cs
> +using System.Threading.Tasks;
Хорошо

2018-10-17 08:21 UTC, egorikas commented on test/ServiceHost.Tests/ServiceHost.Tests.csproj
> +    <PackageReference Include="Moq" Version="4.10.0" />
Это на будущее. Я начала писать с моком IConfiguration, потом понял, что слишком сложная структура мока и решил добавить тестовый файл. + в будущем тесты же с моками, а ничего удобнее moq я пока на .NET не видел

2018-10-17 08:21 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            await botClient.SendTextMessageAsync(_settings.ChannelName, text).ConfigureAwait(false);
Да, мне тоже было бы интересно. Я тестировал на plain-text

2018-10-17 08:39 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Как мы говорили пароли будут динамически загружаться откуда-нибудь. Т.е. будет какой-то SecretManager. Соответственно, в класс хотели передавать интерфейс, для получения настроек. Можно свой, который будет в Infrastructure.Telegram, но можно IOptions, не вижу в этом особой проблемы
Потом мы этот интерфейс просто реализуем в SecretManager

2018-10-17 08:41 UTC, Sergey-Buyanov commented on test/ServiceHost.Tests/ServiceHost.Tests.csproj
> +    <PackageReference Include="Moq" Version="4.10.0" />
Понятно )
Да, в тестах мы используем Moq

2018-10-17 08:41 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Просто они все равно будут в виде  IOptions<TelegramSettings> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1
Поэтому я не всегда вижу смысл в IOptions. Если нам hot-reload нужен, то возможно. Но как мне видится, возможность этого минимальна

2018-10-17 08:46 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Да, как раз hot-reload нужен будет, например, когда с токеном, что-то не то мы просто его меняем, без передеплоя сервера

2018-10-17 08:46 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Тогда ок, добавлю

2018-10-22 19:44 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(TelegramGatewaySettings settings)
Как оказалось, при использовании autofac не так просто сделать inject IOptions. Я изрядно поковырялся во внутрянке и решил не тащит эти сложные штуки в проект, т.к. они не особо понятны. Убрал AsSingletone, чтобы настройки забирались каждый раз

2018-10-22 19:45 UTC, egorikas commented
@Sergey-Buyanov поправил замечания, за исключением IOptions. Autofac оказался сильнее IOptions

2018-10-22 20:13 UTC, egorikas commented
@Sergey-Buyanov Сделано

2018-10-23 18:08 UTC, Sergey-Buyanov requested changes

2018-10-23 18:08 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(IOptions<TelegramGatewaySettings> settings)
Add null check validation

2018-10-23 18:08 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            var botClient = new TelegramBotClient(_settings.Value.AuthToken);
Introduce variable telegramSettings = _settings.Value;
Для атомарности и чтобы несколько раз не запрашивать данные из хранилища

2018-10-23 18:08 UTC, Sergey-Buyanov commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
Вроде был ConfigurationModule в котором регистрировались Options
Проблемы с регистрацией IOptions возникли из-за того, что не было её реализации
Думаю просто нужно добавить реализацию например
OptionsManager : IOptions<TelegramSettings>
  public OptionsManager(IConfiguration)
 в ServiceHost, зарегестрируй её всё заработает

ConfigureSettings просто ещё неявно регистрирует свои реализации для IOptions, поэтому и работает )

2018-10-23 18:08 UTC, Sergey-Buyanov commented on test/ServiceHost.Tests/AutofacModules/AutofacModulesTest.cs
> +        private static void ConfigureMockSettings(ContainerBuilder builder)
Если сделать реализацию OptionsManager о чем писал выше,  то Мосk не нужен

2018-10-24 15:51 UTC, egorikas commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
Я немного не понял. ConfigurationModule я делал руками.
В чем проблема IOptions, они очень сильно завязаны на ConfigureSettings. Там внутри происходит вакханалия (я хорошо исходники посмотрел) и получить instance у IOptions достаточно не тривиально.

2018-10-24 15:53 UTC, egorikas commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
Создать Instance у IOptions достаточно не тривиально, я подробно просмотрел исходники, местами там очень сильная вакханалия творится.
Относледование от IOptions мне видится грязным хаком, т.к. это воспринимается как абстракция ради абстракции, если мы хотим использовать IOptions, то нужно использовать его. Какой смысл в том, чтобы сделать свою реализацию и просто каждый раз ходить в IConfiguration?

2018-10-24 15:54 UTC, egorikas commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
То есть, логичными выглядят 2 пути:

2018-10-24 15:55 UTC, egorikas commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
Логичными выглядят 2 пути:
1) Наша реализация опций (придется городить городушки с интерфейсами и прочим)
2) Чистая реализация с IOptions

А делать дикую смесь из IOptions и нашего кода, как по мне, не очень логично

2018-10-24 15:56 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(IOptions<TelegramGatewaySettings> settings)
А чисто в теории, разве может DI вернуть здесь null? Не упадет ли он на этапе построения графа зависимостей?

2018-10-24 15:57 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            var botClient = new TelegramBotClient(_settings.Value.AuthToken);
Тогда мы теряем hot-reload который обсуждали выше. Потому что будем хранить жесткую ссылка на какую-то копию настроек

2018-10-24 20:07 UTC, Sergey-Buyanov commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
IOptions это просто удобный интерфейс, который предоставляет .NET Core, также он предоставляет их реализации, которые можно использовать (OptionsManager<>, OptionsWrapper<> и т.п. их .NET неявно регистрирует при вызове соответсвующих методов)
Как я вижу, у нас будет загрузка конфигурации (например, пароля) не только из конфига, но из других мест, пока не известно. То есть будет своя реализация IOptions (используя  реализации .NET Core  или свои). Чтобы сейчас с этим не заморачиваться и как-то протестировать код. Я предлагаю просто сделать простую её реализацию

>Создать Instance у IOptions достаточно не тривиально
Почему? создать класс 
`OptionsManager: IOptions<TelegramSettings>`
при регистрации в Autofac 
`builder.RegisterType<OptionsManager>().AsImplementedInterface();`
или что-то другое имел в виду?

>Относледование от IOptions мне видится грязным хаком, т.к. это воспринимается как абстракция ради абстракции, если мы хотим использовать IOptions, то нужно использовать его. Какой смысл в том, чтобы сделать свою реализацию и просто каждый раз ходить в IConfiguration?
Да в классах хотелось использовать IOptions, а в реализации помимо IConfiguration, как говорил скорей всего будем ходить ещё в другие места

2018-10-24 20:13 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            var botClient = new TelegramBotClient(_settings.Value.AuthToken);
Я имел в виду создать не член класса, а временную переменную в методе. При каждом вызове будет зачитываться значение

2018-10-24 20:24 UTC, Sergey-Buyanov commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(IOptions<TelegramGatewaySettings> settings)
Да, исхожу из того, что класс можно создать разными способами, иногда не очень явными. В Autofac это можно сделать используя ResolveOptional
Да и стараюсь придерживаться правила проверять параметры public методов, во избежание недоразумений и поиску ошибок с NullReferenceException )

2018-10-25 07:59 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +        public TelegramGateway(IOptions<TelegramGatewaySettings> settings)
Согласен

2018-10-25 07:59 UTC, egorikas commented on src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.Telegram/TelegramGateway.cs
> +            var botClient = new TelegramBotClient(_settings.Value.AuthToken);
Согласен

2018-10-25 08:00 UTC, egorikas commented on src/ServiceHost/Autofac/SettingsExtensions.cs
> +﻿using Microsoft.Extensions.DependencyInjection;
Хорошо, я понял позицию, сделаю

2019-04-18 19:30 UTC, egorikas commented
Реквест не актуален

2019-04-18 19:30 UTC, closed without merging