import images from AuditDB, allow to get logos for friends, avatars f…
DotNetRu/Server pull request #77
Opened 2019-05-09 22:25 UTC by MaxShoshin

…or spekers

2019-05-10 17:06 UTC, egorikas commented
Спасибо за реквест, смогу посмотреть в субботу или вск

2019-05-12 17:15 UTC, egorikas requested changes
Спасибо за работу! 
Есть 2 мелких замечания и 1 серьезное

По серьезному, я не доработал задачу видимо. Но смысл в том, что мы хотим отвязаться от аудита в папочке и хранить все в базе. 

Сейчас есть контроллер `FileController` и он позволяет загружать фотографии для друзей и и прочего. И он уже не ложится на схему которая сейчас есть.

Я предлагаю сделать нормальные внешние ключи на `Image`, а не искать их по адресам. Мы тогда сможем делать с картинками что хотим (удалять, добавлять и прочее)

2019-05-12 17:15 UTC, egorikas commented on DotNetRuServer.Importer/Program.cs
> +            _context.Images.Add(new ImageData
Мне кажется, что есть смысл сделать `AddAsync` и `SaveChangesAsync` здесь. Иначе получается ситуация, что, что-то синхронное, а что-то нет

2019-05-12 17:15 UTC, egorikas commented on DotNetRuServer.Meetups.BL/Services/ImageService.cs
> +            return image.ToVm();
Можно сделать image?.ToVm()

2019-05-12 17:16 UTC, egorikas commented on DotNetRuServer.Migrations/12_AddImagesTable.cs
> +                .WithColumn("ExternalUrl")
К ситуации с общей моделью. Думается мне, что `ExternalUrl` вообще не нужен здесь. Есть картинка, а как мы ее экспортировать будем - задача экспортера

2019-05-12 17:18 UTC, egorikas commented on DotNetRuServer.Importer/Program.cs
> +                        AvatarUrl = avatar.DownloadUrl,
`AvatarUrl` и `AvatarSmallUrl` наследие дней, когда было не понятно, что хотим сделать с картинками. Их смело можно дропнуть и сделать нормальные внешние ключи (относится и к другим моделям)

2019-05-14 17:15 UTC, egorikas commented
@MaxShoshin ты планируешь переделать реквест? Если нет, то просто вмержим как написал и еще задачку поставлю.

2019-05-16 19:09 UTC, MaxShoshin commented
Да, планирую исправить.

2019-05-28 15:42 UTC, egorikas commented
@MaxShoshin привет! не удалось посмотреть? Просто мы немного упираемся в картинки, чтобы дальнейший функционал можно было делать

2019-06-05 21:03 UTC, MaxShoshin commented on DotNetRuServer.Migrations/12_AddImagesTable.cs
> +                .WithColumn("ExternalUrl")
Пока оставил, чтобы одинаковые картинки не грузить. Используется только при импорте и больше нигде не используется.

2019-06-05 22:18 UTC, MaxShoshin commented on DotNetRuServer.Importer/Program.cs
> +                        AvatarUrl = avatar.DownloadUrl,
Хорошо

2019-06-06 19:29 UTC, merged