Заменил Autofac на стандартный контейнер
DotNetRu/Server pull request #95
Opened 2019-10-10 18:28 UTC by rafaelldi

Я не большой знаток Autofac, так что лучше внимательно посмотреть, правильно ли всё перенёс

2019-10-10 18:33 UTC, Sergey-Buyanov commented on DotNetRuServer.Meetups.BL/MeetupServiceCollectionExtension.cs
> +            services.AddSingleton<ICommunityService, CommunityService>();
Вопрос по поводу использования синглетон, реализации у нас thread safe?

2019-10-11 11:05 UTC, egorikas commented on DotNetRuServer.Meetups.BL/MeetupServiceCollectionExtension.cs
> +            services.AddSingleton<ICommunityService, CommunityService>();
Меня это тоже смущает, НО у нас прямо нашего стейта нигде нет, мы либо EF дергаем, либо ICache

2019-10-11 11:05 UTC, egorikas approved these changes

2019-10-11 11:06 UTC, egorikas commented on DotNetRuServer.Meetups.BL/MeetupServiceCollectionExtension.cs
> +            services.AddSingleton<ICommunityService, CommunityService>();
@AnatolyKulakov рассуди нас :)

2019-10-11 11:07 UTC, egorikas requested changes
Предлагаю выпилить Singletone и сделать как Transient, тогда точно не схватим интересных сайд-эффектов

2019-10-11 11:45 UTC, Sergey-Buyanov commented
В принципе скорей всего достаточно Scoped, тогда видимость будет per request, но не будет оверхеда на создание новых объектов, на каждую зависимость в классах

2019-10-11 12:45 UTC, rafaelldi commented
Вроде бы в Autofac были синглтоны, поэтому так и перенёс. Ок, поправлю.

Я так понимаю, что `MemCache` остаётся `Singleton`, а на `Scoped` изменить всё в файле `MeetupServiceCollectionExtension.cs`? Кстати, для `Settings` есть механизм `IOptions`, наверное, стоит заиспользовать его.

2019-10-11 13:02 UTC, egorikas commented
Да, хорошая идея с IOptions

2019-10-11 13:02 UTC, egorikas commented
я через пару часов запущу и тогда замержу

2019-10-12 11:17 UTC, merged